# Generated by Django 4.1.7 on 2023-03-17 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='category_PostCategory',
        ),
        migrations.AddField(
            model_name='postcategory',
            name='category_PostCategory',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
            preserve_default=False,
        ),
    ]
